plot_hole/models.py
from datetime import datetime
from plot_hole import db, login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(id):
    return User.objects(id=id).first()


class User(UserMixin, db.Document):
    email = db.EmailField(unique=True)
    username = db.StringField(max_length=50)
    password = db.StringField()
    meta = {"allow_inheritance": True}


class Plot(db.Document):
    plot = db.PointField()
    plot_date = db.DateTimeField(default=datetime.utcnow)
    user = db.ReferenceField(User)

plot_hole/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import (
    DataRequired,
    Length,
    Email,
    EqualTo,
    ValidationError,
)
from plot_hole.models import User


class RegistrationForm(FlaskForm):
    email = StringField("email", validators=[DataRequired(), Email()])
    password = PasswordField("password", validators=[DataRequired()])
    confirm_password = PasswordField(
        validators=[DataRequired(), EqualTo("password", "use same password!")]
    )
    submit = SubmitField()

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError("User already exists")

    def validate_email(self, email):
        email = User.query.filter_by(email=email.data).first()
        if email:
            raise ValidationError("User already exists")


class LoginForm(FlaskForm):
    email = StringField("email", validators=[DataRequired(), Email()])
    password = PasswordField("password", validators=[DataRequired()])
    # remember = BooleanField('remember')
    submit = SubmitField()


class PlotForm(FlaskForm):
    lat = StringField("Lat", validators=[DataRequired()])
    long = StringField("Long", validators=[DataRequired()])
    submit = SubmitField("Plot")

plot_hole/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import FloatField, SubmitField
from wtforms.validators import DataRequired


class PlotForm(FlaskForm):
    lat = FloatField("Lat", validators=[DataRequired()])
    long = FloatField("Long", validators=[DataRequired()])
    submit = SubmitField("Plot")

plot_hole/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import (
    DataRequired,
    Length,
    Email,
    EqualTo,
    ValidationError,
)
from plot_hole.models import User


class RegistrationForm(FlaskForm):
    email = StringField("email", validators=[DataRequired(), Email()])
    password = PasswordField("password", validators=[DataRequired()])
    confirm_password = PasswordField(
        validators=[DataRequired(), EqualTo("password", "use same password!")]
    )
    submit = SubmitField()

    def validate_email(self, email):
        email = User.objects(email=email.data)
        if email:
            raise ValidationError("User already exists")


class LoginForm(FlaskForm):
    email = StringField("email", validators=[DataRequired(), Email()])
    password = PasswordField("password", validators=[DataRequired()])
    # remember = BooleanField('remember')
    submit = SubmitField()

plot_hole/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mongoengine import MongoEngine

app = Flask(__name__)
app.config["SECRET_KEY"] = "a4f2d0f8ca8ffdf793fe0b9a0562f32e"
# app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///site.db"
# db = SQLAlchemy(app)
db = MongoEngine(app)
bcrypt = Bcrypt(app)

login_manager = LoginManager(app)
login_manager.login_view = "users.login"

from plot_hole.main.routes import main
from plot_hole.posts.routes import posts
from plot_hole.users.routes import users

app.register_blueprint(main)
app.register_blueprint(posts)
app.register_blueprint(users)

plot_hole/main/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint

main = Blueprint("main", __name__)


@main.route("/", methods=("GET", "POST"))
def home():
    return render_template("home.html")


@main.route("/about")
def about():
    return render_template("about.html")

plot_hole/posts/routes.py
from flask import (
    render_template,
    url_for,
    flash,
    redirect,
    request,
    Blueprint,
    jsonify,
)
from flask_login import login_user, current_user, logout_user, login_required
from plot_hole import db
from plot_hole.models import Plot
from plot_hole.posts.forms import PlotForm

posts = Blueprint("posts", __name__)


@posts.route("/map", methods=("GET", "POST"))
def map():
    form = PlotForm()
    plots = Plot.objects()

    if form.validate_on_submit():
        plot = Plot(plot=[form.lat.data, form.long.data], user=current_user.id)
        plot.save()
        flash("Plotted!", "is-primary")
        return redirect(url_for("posts.map"))
    return render_template(
        "map.html", form=form, plots=[plot for plot in plots]
    )


@posts.route("/plots/")
def plots():
    plots = Plot.objects()
    return jsonify([plot for plot in plots])


@posts.route("/plot_pothole")
def plot_pothole():
    longitude = request.args.get("longitude", type=float)
    latitude = request.args.get("latitude", type=float)

    if current_user.is_authenticated:
        plot = Plot(plot=[longitude, latitude], user=current_user.id)
        plot.save()
        flash("Plotted!", "is-primary")
        return redirect(url_for("posts.map"))
        # return render_template("map.html")
    flash("You must be logged in to do that!", "is-warning")
    return render_template("map.html", form=form)

plot_hole/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from plot_hole import db, bcrypt
from plot_hole.users.forms import RegistrationForm, LoginForm
from plot_hole.models import User, Plot

users = Blueprint("users", __name__)


@users.route("/register", methods=("GET", "POST"))
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data
        ).decode("utf-8")

        user = User(
            username=form.email.data,
            email=form.email.data,
            password=hashed_password,
        )
        user.save()

        flash(f"Account created for {form.email.data}!")
        return redirect(url_for("users.login"))
    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=("GET", "POST"))
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
            user.password, form.password.data
        ):
            login_user(user, remember=False)
            next_page = request.args.get("next")
            flash("You have been logged in!")
            return (
                redirect(next_page)
                if next_page
                else redirect(url_for("users.account"))
            )
        else:
            flash("Login Unsuccessful - Check Email or Password")
    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))


@users.route("/account")
@login_required
def account():
    count = Plot.objects(user=current_user.id).count()
    plots = Plot.objects(user=current_user.id)

    return render_template(
        "account.html",
        title="Account",
        count=count,
        plots=[plot for plot in plots],
    )

plot_hole/templates/about.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="box">
    <div class="content has-text-grey-light">
      <h1>New Orleans has a pothole problem</h1>
        <p>
          New Orleans has a pothole problem that our government
          simply cant keep up with. What is additionally frustrating is the lack
          of a simple way to document where our city needs some help.
        </p>
        <p>
          Plothole aims to make it simple for residents
          to report where there are issues.
        </p>

      <h2>How New Orleans currently does it</h2>
        <p>
          Per the city's [website](https://nola.gov/dpw/potholes/),
          you can call 311 Monday through Friday during work hours and
          speak to a representative and tell them where the pothole is.
          You can also go [here](https://nola311.org/) and fill out a
          'request form' and describe the location of the pothole.
        </p>
        <p>
          There are three huge flaws with reporting in this way.
        </p>
        <ol type="1">
          <li>Free-text field forms lack structure and make it difficult if not impossible to aggregate data</li>
          <li>The city provides no way of reporting multiple potholes at once.</li>
          <li>There is no signal back to the resident that their concern will be actually noticed.</li>
        </ol>

      <h2>How Plothole does it</h2>
        <p>
          Plothole makes plotting potholes simple **and** accurate by
          providing a detailed map of New Orleans with a draggable marker
          that pinpoints the exact location of the pothole.
          Alongside location data Plothole can also collect
          information about the pothole such as:
        </p>
        <ol>
          <li>approximate size</li>
          <li>approximate depth</li>
          <li>time of first appearance</li>
          <li>current status (filled/not-filled)</li>
        </ol>
        <p>
          Plothole will also allow residents to upload photos of as well as
          subscribe to potholes around the city.
        </p>
    </div>
  </div>
</div>
{% endblock %}

plot_hole/templates/account.html
{% extends "base.html" %}

{% block content %}


  <div class="columns">
    <div class="column is-one-quarter">
      <div class="container">
        <h1 class="title has-text-grey-lighter">
          Hello, {{ current_user.username }}!
        </h1>
        <h2 class="subtitle has-text-grey-lighter">
          You have plotted {{ count }} potholes!
        </h2>
        <a class="button is-outlined is-light is-rounded is-small"
                  href={{ url_for("users.logout") }}>Logout
        </a>
      </div>
    </div>
    <div class="container">
      <div class="box">
        <div style="max-height:500px;overflow:auto;">
          <table class="table is-hoverable">
            <tbody>
              {% for plot in plots %}
              <tr>
                <article class="media">
                  <figure class="media-left">
                    <p class="image is-128x128">
                      <img src="https://bulma.io/images/placeholders/128x128.png">
                    </p>
                  </figure>
                  <div class="media-content">
                    <div class="content">
                      <p class="title is-4"> {{ plot.plot.type }} </p>
                      <p class="subtitle is-6"> {{ plot.plot_date }} </p>
                      <div class="content">
                        {{ plot.plot.coordinates }}
                      </div>
                    </div>
                    <nav class="level is-mobile">
                      <div class="level-left">
                        <div class="buttons">
                          <button class="button is-info is-light is-small">Update</button>
                          <button class="button is-danger is-light is-small">Delete</button>
                        </div>
                      </div>
                    </nav>
                  </div>
                </article>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

plot_hole/templates/base.html
<!DOCTYPE html>
<html>
{% include "includes/header.html" %}

  <body>
    {% include "includes/navbar.html" %}
    <section class="hero is-fullheight">
      <div class="hero-body">
        <div class='container'>

          {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
          {% for category, message in messages %}
          <div class="notification is-primary has-text-centered">
            {{ message }}
          </div>
          {% endfor %}
          {% endif %}
          {% endwith %}

          {% block content %}
          {% endblock %}


        </div>
      </div>
    </section>
  </body>

{% include "includes/footer.html" %}
</html>

plot_hole/templates/home.html
{% extends "base.html" %}

{% block content %}

  <div class="subtitle is-4 has-text-centered has-text-white">
    PlotHole is a plotter for potholes.
    <br>
    Made in <strong class="has-text-primary">New Orleans.</strong>
    <br>
    <br>
    <a class="button is-white is-outlined is-large is-rounded" href={{ url_for("posts.map") }}>
      Plot!
    </a>
  </div>
{% endblock %}

{% block about %}
  <section>
    sadfsaf
  </section>

{% endblock %}

plot_hole/templates/includes/footer.html
<footer class="footer has-background-light">
  <div class="content has-text-centered has-text-grey">
  <p>
  <strong>PlotHole</strong> by Patrick Trainer.
  </p>
  </div>
</footer>

plot_hole/templates/includes/header.html
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Plot Potholes - PlotHole</title>


  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  <link rel="stylesheet" href="/static/css/mystyles.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
  <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.5.0/mapbox-gl.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.5.0/mapbox-gl.css' rel='stylesheet' />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  
  <style>
    /* background */
    .hero {
      background: url("/static/nola_streets_bw.png") center / cover;
    }
  </style>


</head>

plot_hole/templates/includes/navbar.html
<nav class="navbar">

  <div class="navbar-brand">
    <a class="navbar-item" href={{ url_for("main.home") }}>
      P l o t H o l e
    </a>
  </div>

    <div class="navbar-burger" onclick="document.querySelector('.navbar-burger').classList.toggle('is-active');
      document.querySelector('.navbar-menu').classList.toggle('is-active');">
      <span></span>
      <span></span>
      <span></span>
    </div>

    <div class="navbar-menu">
      <a class="navbar-item" href={{ url_for("posts.map") }}>
        Map
      </a>
      <a class="navbar-item" href={{ url_for("main.about") }}>
        About
      </a>
      {% if current_user.is_authenticated %}

      <a class="navbar-item" href={{ url_for("users.account") }}>
        Account
      </a>
      {% else %}
      <a class="navbar-item" href={{ url_for("users.login") }}>
        Login
      </a>
      <a class="navbar-item" href={{ url_for("users.register") }}>
        Register
      </a>
      {% endif %}
    </div>

</nav>

plot_hole/templates/includes/plot_form.html
<div class="columns is-mobile is-centered">
  <div class="column is-half">
    <form method="POST" action="">
      {{ form.hidden_tag() }}

      <div class="field">
        <p class="control">
          {{ form.lat(class="input", placeholder="Lat") }}
        </p>
      </div>

      <div class="field">
        <p class="control">
          {{ form.long(class="input", placeholder="Long") }}
        </p>
      </div>

      <div class="field">
        <p class="control">
          {{ form.submit(class="button is-primary is-outlined is-rounded")}}
        </p>
      </div>

    </form>
  </div>
</div>

plot_hole/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="columns is-mobile is-centered">
  <div class="column is-half">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <div class="field">

        <p class="control has-icons-left has-icons-right">
          {{ form.email(class="input", placeholder="Email") }}
          <span class="icon is-small is-left">
            <i class="fas fa-envelope"></i>
          </span>
          <span class="icon is-small is-right">
            <i class="fas fa-check"></i>
          </span>
        </p>

      </div>

      <div class="field">
        <p class="control has-icons-left">
          {{ form.password(class="input", placeholder="Password") }}
          <span class="icon is-small is-left">
            <i class="fas fa-lock"></i>
          </span>
        </p>
      </div>

      <div class="field">
        <p class="control">
          {{ form.submit(class="button is-primary is-outlined is-rounded")}}
        </p>
      </div>
    </form>
  </div>
</div>
{% endblock %}

plot_hole/templates/map.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
   integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
   crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
      integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
      crossorigin="">
    </script>
    <script src="https://leaflet.github.io/Leaflet.heat/dist/leaflet-heat.js">
    </script>

<div class="level">
  <div class="level-item">
    <div id='map' style='width: 820px;
         height: 640px;'>
    </div>


    <script>
      var mymap = L.map('map').setView([29.95 ,-90.11], 12);
      L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
          attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
          maxZoom: 18,
          id: 'mapbox/dark-v10',
          tileSize: 512,
          zoomOffset: -1,
          accessToken: 'pk.eyJ1IjoianNvbWEiLCJhIjoibFJmYl9JWSJ9.AUm8d76cbOvVEn2mMeG_ZA'
      }).addTo(mymap);


    $(document).ready(function(){
      $("button").click(function(){
        $.get("{{ url_for("posts.plots") }}",
        function(data,status){
          alert("Data:" + data);
        });
      });
    });

      var popup = L.popup();
      mymap.on('click', function(e){
          var coord = e.latlng;
          var lat = coord.lat;
          var lng = coord.lng;
          var newMarker = L.marker(e.latlng, {draggable:'true'}).addTo(mymap)
          .bindPopup().openPopup();
      });

      var coord = [{% for plot in plots %}
      	          {{ [plot.plot.coordinates[1],plot.plot.coordinates[0]]|tojson|safe }}, // lat, lng, intensity
                  {% endfor %}];

      var heat = L.heatLayer(
          coord
        , {radius: 10,
           maxZoom: 15}).addTo(mymap);

    </script>

  </div>

    <button>Plot a pothole</button>

</div>

{% endblock %}

plot_hole/templates/plot.html
{% extends "base.html" %}

{% block content %}
<h1 class="title has-text-grey-lighter">
  {% for p in plot %}
   {{ p.plot }}
  {% endfor %}
</h1>
{% endblock %}

plot_hole/templates/plot_form.html
<div class="columns is-mobile is-centered">
  <div class="column is-half">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <div class="field">

        <p class="control has-icons-left has-icons-right">
          {{ form.lat(class="input", placeholder="Lat") }}
          <span class="icon is-small is-left">
            <i class="fas fa-envelope"></i>
          </span>
          <span class="icon is-small is-right">
            <i class="fas fa-check"></i>
          </span>
        </p>

      </div>

      <div class="field">
        <p class="control has-icons-left">
          {{ form.long(class="input", placeholder="Long") }}
          <span class="icon is-small is-left">
            <i class="fas fa-lock"></i>
          </span>
        </p>
      </div>

      <div class="field">
        <p class="control">
          {{ form.submit(class="button is-primary is-outlined is-rounded")}}
          </button>
        </p>
      </div>
    </form>
  </div>
</div>

plot_hole/templates/register.html
{% extends "base.html" %}

{% block content %}
<div class="columns is-mobile is-centered">

  <div class="column is-half">
    <form method="POST" action="">
      {{ form.hidden_tag() }}

      <div class="field">
          {{ form.email(class="input", placeholder="Email") }}
      </div>

      <div class="field">
          {{ form.password(class="input", placeholder="Password") }}
      </div>

      <div class="field">
          {{ form.confirm_password(class="input", placeholder="Confirm Password") }}

      </div>

      <div class="field">

          {{ form.submit(class="button is-primary is-outlined is-rounded")}}

      </div>
    </form>

    <div class="container">
      <div class="content has-text-centered has-text-grey">
        <p>
          <br>
          Already have an account?
          <br>
          <br>
          <a class="button is-light is-outlined" href={{ url_for("users.login") }}>
            login
          </a>
        </p>
      </div>
    </div>
  </div>
</div>

{% endblock %}